# Generated by Django 4.1.1 on 2022-09-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_loginuser_email_alter_loginuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='프로필이미지'),
        ),
    ]
